## Specify the handlers
#handlers = java.util.logging.ConsoleHandler
#
## Default global logging level
#.level = INFO
#
## ConsoleHandler properties
#java.util.logging.ConsoleHandler.level = INFO
#java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
#
## Customize logging levels for specific loggers (optional)
## For example, to set a different logging level for the library package
#library.level = FINE
